model:
  path: checkpoints/NMSKuantumModel.pt
  num_continuous: 33
  categories: []
  dim: 32
  depth: 4
  heads: 8
  dim_head: 16
  dim_out: 3
  attn_dropout: 0.1
  ff_dropout: 0.1
  lastmlp_dropout: 0.0
  cont_embeddings: MLP
  attentiontype: col
scaler:
  path: checkpoints/NMSKuantumScaler.pkl
device: auto
